import "ExplorerItem.idl";
import "RegExShortcut.idl";

namespace PowerRenameUI_new
{
    [default_interface]
    runtimeclass MainWindow : Windows.UI.Xaml.Controls.UserControl
    {
        MainWindow();
        Windows.Foundation.Collections.IObservableVector<ExplorerItem> ExplorerItems { get; };
        Windows.Foundation.Collections.IObservableVector<RegExShortcut> SearchRegExShortcuts { get; };
        Windows.Foundation.Collections.IObservableVector<RegExShortcut> FileRegExShortcuts { get; };

        Windows.UI.Xaml.Controls.TextBox TextBoxSearch();
        Windows.UI.Xaml.Controls.TextBox TextBoxReplace();
        
        Windows.UI.Xaml.Controls.CheckBox ChckBoxRegex();
        Windows.UI.Xaml.Controls.CheckBox ChckBoxCaseSensitive();
        Windows.UI.Xaml.Controls.CheckBox ChckBoxMatchAll();
        Windows.UI.Xaml.Controls.Primitives.ToggleButton TglBtnEnumerateItems();

        Windows.UI.Xaml.Controls.ComboBox ComboBoxRenameParts();

        Windows.UI.Xaml.Controls.Primitives.ToggleButton TglBtnIncludeFiles();
        Windows.UI.Xaml.Controls.Primitives.ToggleButton TglBtnIncludeFolders();
        Windows.UI.Xaml.Controls.Primitives.ToggleButton TglBtnIncludeSubfolders();

        Windows.UI.Xaml.Controls.Button BtnRename();
        
        Windows.UI.Xaml.Controls.Primitives.ToggleButton TglBtnUpperCase();
        Windows.UI.Xaml.Controls.Primitives.ToggleButton TglBtnLowerCase();
        Windows.UI.Xaml.Controls.Primitives.ToggleButton TglBtnTitleCase();
        Windows.UI.Xaml.Controls.Primitives.ToggleButton TglBtnCapitalize();

        void AddExplorerItem(Int32 id, String original, Int32 type, Int32 parentId);
        void UpdateExplorerItem(Int32 id, String newName);
    }
}
