import "ExplorerItem.idl";
import "RegExShortcut.idl";

namespace PowerRenameUI_new
{
    [default_interface]
    runtimeclass MainWindow : Windows.UI.Xaml.Controls.UserControl
    {
        MainWindow();
        Windows.Foundation.Collections.IObservableVector<ExplorerItem> ExplorerItems { get; };
        Windows.Foundation.Collections.IObservableVector<RegExShortcut> SearchRegExShortcuts { get; };
        Windows.Foundation.Collections.IObservableVector<RegExShortcut> FileRegExShortcuts { get; };

        Windows.UI.Xaml.Controls.CheckBox ChckBoxRegex();
        Windows.UI.Xaml.Controls.CheckBox ChckBoxCaseSensitive();
        Windows.UI.Xaml.Controls.CheckBox ChckBoxNameOnly();
        Windows.UI.Xaml.Controls.CheckBox ChckBoxExtensionOnly();
        Windows.UI.Xaml.Controls.CheckBox ChckBoxMatchAll();
        Windows.UI.Xaml.Controls.CheckBox ChckBoxExcludeFiles();
        Windows.UI.Xaml.Controls.CheckBox ChckBoxExcludeFolders();
        Windows.UI.Xaml.Controls.CheckBox ChckBoxExcludeSubfolders();
        Windows.UI.Xaml.Controls.CheckBox ChckBoxEnumerateItems();

        void AddExplorerItem(Int32 id, String original, Int32 type, Int32 parentId);
    }
}
